/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVFVHQVMgS1VMSUFIL0tFTEFTMi9TRU1FU1RFUiA0L1dlYiBMYW5qdXQvQkVMQUpBUkFOR1VMQVIvUHJha3Rpa3VtMS9wcmFrMy9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovVFVHQVMgS1VMSUFIL0tFTEFTMi9TRU1FU1RFUiA0L1dlYiBMYW5qdXQvQkVMQUpBUkFOR1VMQVIvUHJha3Rpa3VtMS9wcmFrMy9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
