/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVFVHQVMgS1VMSUFIL0tFTEFTMi9TRU1FU1RFUiA0L1dlYiBMYW5qdXQvQkVMQUpBUkFOR1VMQVIvUHJha3Rpa3VtMS9wcmFrMy9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9UVUdBUyBLVUxJQUgvS0VMQVMyL1NFTUVTVEVSIDQvV2ViIExhbmp1dC9CRUxBSkFSQU5HVUxBUi9QcmFrdGlrdW0xL3ByYWszL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
